producer: 
  mod_name: shenhe_voice
  config: [132, 0.3, 0.668, 1.0]
  filter_center: 150

gambler:  
  mod_name: huhtao_voice
  config: [119, 0.5, 0.668, 1.0]
  filter_center: 150

mechanic:
  mod_name: ying_voice
  config: [ 91, 0.4, 0.668, 1.0]
  filter_center: 150

coach:    
  mod_name: keqing_voice
  config: [115, 0.3, 0.668, 1.0]
  filter_center: 150

namvet:
  mod_name: wendi_voice
  config: [ 97, 0.3, 0.668, 1.0]
  filter_center: 150

# biker:
#   mod_name: luoshaliya_voice
#   config: [118, 0.2, 0.668, 1.0]
#   filter_center: 150

biker:
  mod_name: jiuqiren_voice
  config: [136, 0.5, 0.5, 1.0]
  filter_center: 150

manager:
  mod_name: bachongshenzi_voice
  config: [133, 0.5, 0.5, 1.0]
  filter_center: 150

teengirl:
  mod_name: xiaogong_voice
  config: [122, 0.5, 0.5, 1.0]
  filter_center: 150

# teengirl:
#   mod_name: ailixiya_voice
#   config: [226, 0.5, 0.5, 1.0]
#   filter_center: 150

whitaker:
  mod_name: npc_voice
  config: [157, 0.1, 0.4, 1.0]

virgil:
  mod_name: npc_voice
  config: [ 97, 0.3, 0.4, 1.0]

soldier1: 
  mod_name: npc_voice
  config: [118, 0.1, 0.2, 1.0]

soldier2:
  mod_name: npc_voice
  config: [ 93, 0.1, 0.2, 1.0]