# Rochelle
producer: 
  mod_name: 妖精aili_voice
  config: [215, 0.3, 0.668, 1.0]
  filter_center: 150

# Nick
gambler:  
  mod_name: ludike_voice
  config: [94, 0.5, 0.668, 1.0]
  filter_center: 150

# Ellis
mechanic:
  mod_name: kiana_voice
  config: [228, 0.3, 0.668, 1.0]
  filter_center: 200

# 教练
coach:
  mod_name: theresa_voice
  config: [205, 0.2, 0.668, 1.0]
  filter_center: 350

# 比尔
namvet:
  mod_name: wendi_voice
  config: [ 97, 0.3, 0.668, 1.0]
  filter_center: 150

# biker:
#   mod_name: luoshaliya_voice
#   config: [118, 0.2, 0.668, 1.0]
#   filter_center: 150

# 弗朗西斯
biker:
  mod_name: ayaka_voice
  config: [87, 0.3, 0.5, 1.0]
  filter_center: 150

# 路易斯
manager:
  mod_name: shizhilvzhe_voice
  config: [233, 0.3, 0.5, 1.0]
  filter_center: 150

# 佐伊
teengirl:
  mod_name: keqing_voice
  config: [115, 0.3, 0.5, 1.0]
  filter_center: 150

# teengirl:
#   mod_name: ailixiya_voice
#   config: [226, 0.5, 0.5, 1.0]
#   filter_center: 150

whitaker:
  mod_name: npc_voice
  config: [157, 0.1, 0.4, 1.0]

virgil:
  mod_name: npc_voice
  config: [ 97, 0.3, 0.4, 1.0]

soldier1:
  mod_name: npc_voice
  config: [118, 0.1, 0.2, 1.0]

soldier2:
  mod_name: npc_voice
  config: [ 93, 0.1, 0.2, 1.0]